package ec.edu.ups.g1.prueba.evaluacionwspalta.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2021-02-27T14:56:42.657-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "ClienteServicioSOAPService", 
                  wsdlLocation = "http://localhost:8080/EvaluacionWSPALTA/ClienteServicioSOAP?wsdl",
                  targetNamespace = "http://servicio.EvaluacionWSPALTA.prueba.g1.ups.edu.ec/") 
public class ClienteServicioSOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicio.EvaluacionWSPALTA.prueba.g1.ups.edu.ec/", "ClienteServicioSOAPService");
    public final static QName ClienteServicioSOAPPort = new QName("http://servicio.EvaluacionWSPALTA.prueba.g1.ups.edu.ec/", "ClienteServicioSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/EvaluacionWSPALTA/ClienteServicioSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ClienteServicioSOAPService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/EvaluacionWSPALTA/ClienteServicioSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ClienteServicioSOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ClienteServicioSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteServicioSOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ClienteServicioSOAPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ClienteServicioSOAPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ClienteServicioSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ClienteServicioSOAP
     */
    @WebEndpoint(name = "ClienteServicioSOAPPort")
    public ClienteServicioSOAP getClienteServicioSOAPPort() {
        return super.getPort(ClienteServicioSOAPPort, ClienteServicioSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteServicioSOAP
     */
    @WebEndpoint(name = "ClienteServicioSOAPPort")
    public ClienteServicioSOAP getClienteServicioSOAPPort(WebServiceFeature... features) {
        return super.getPort(ClienteServicioSOAPPort, ClienteServicioSOAP.class, features);
    }

}
