
package ec.edu.ups.g1.prueba.evaluacionwspalta.servicio;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2021-02-27T14:56:42.571-05:00
 * Generated source version: 2.7.11
 * 
 */
public final class ClienteServicioSOAP_ClienteServicioSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://servicio.EvaluacionWSPALTA.prueba.g1.ups.edu.ec/", "ClienteServicioSOAPService");

    private ClienteServicioSOAP_ClienteServicioSOAPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ClienteServicioSOAPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ClienteServicioSOAPService ss = new ClienteServicioSOAPService(wsdlURL, SERVICE_NAME);
        ClienteServicioSOAP port = ss.getClienteServicioSOAPPort();  
        
        {
        System.out.println("Invoking obtenerTituLOS...");
        java.lang.String _obtenerTituLOS_arg0 = "";
        try {
            java.util.List<ec.edu.ups.g1.prueba.evaluacionwspalta.servicio.Titulos> _obtenerTituLOS__return = port.obtenerTituLOS(_obtenerTituLOS_arg0);
            System.out.println("obtenerTituLOS.result=" + _obtenerTituLOS__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking registrarTitulo...");
        java.lang.String _registrarTitulo_arg0 = "";
        java.lang.String _registrarTitulo_arg1 = "";
        java.lang.String _registrarTitulo_arg2 = "";
        try {
            port.registrarTitulo(_registrarTitulo_arg0, _registrarTitulo_arg1, _registrarTitulo_arg2);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
