package ec.edu.ups.g1.prueba.evaluacionwspalta.servicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2021-02-27T14:56:42.651-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://servicio.EvaluacionWSPALTA.prueba.g1.ups.edu.ec/", name = "ClienteServicioSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface ClienteServicioSOAP {

    @WebMethod
    @RequestWrapper(localName = "obtenerTituLOS", targetNamespace = "http://servicio.EvaluacionWSPALTA.prueba.g1.ups.edu.ec/", className = "ec.edu.ups.g1.prueba.evaluacionwspalta.servicio.ObtenerTituLOS")
    @ResponseWrapper(localName = "obtenerTituLOSResponse", targetNamespace = "http://servicio.EvaluacionWSPALTA.prueba.g1.ups.edu.ec/", className = "ec.edu.ups.g1.prueba.evaluacionwspalta.servicio.ObtenerTituLOSResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ec.edu.ups.g1.prueba.evaluacionwspalta.servicio.Titulos> obtenerTituLOS(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "registrarTitulo", targetNamespace = "http://servicio.EvaluacionWSPALTA.prueba.g1.ups.edu.ec/", className = "ec.edu.ups.g1.prueba.evaluacionwspalta.servicio.RegistrarTitulo")
    @ResponseWrapper(localName = "registrarTituloResponse", targetNamespace = "http://servicio.EvaluacionWSPALTA.prueba.g1.ups.edu.ec/", className = "ec.edu.ups.g1.prueba.evaluacionwspalta.servicio.RegistrarTituloResponse")
    public void registrarTitulo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws Exception_Exception;
}
