
package ec.edu.ups.g1.prueba.evaluacionwspalta.servicio;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.11
 * 2021-02-27T14:56:42.645-05:00
 * Generated source version: 2.7.11
 */

@WebFault(name = "Exception", targetNamespace = "http://servicio.EvaluacionWSPALTA.prueba.g1.ups.edu.ec/")
public class Exception_Exception extends java.lang.Exception {
    
    private ec.edu.ups.g1.prueba.evaluacionwspalta.servicio.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, ec.edu.ups.g1.prueba.evaluacionwspalta.servicio.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, ec.edu.ups.g1.prueba.evaluacionwspalta.servicio.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public ec.edu.ups.g1.prueba.evaluacionwspalta.servicio.Exception getFaultInfo() {
        return this.exception;
    }
}
